### ISSUE TITLE
コンテナの制御ができていない

### ISSUE THREAD

**Issue by masibw** [Tomo-9925/cnet#10]
Docker SDKのContainerInspectが返してくるのは`/`付きの名前(例: `/nginx_test`)であるがpolicyには`nginx_test`と記載されているためnginx_testという名前で許可している通信もdropされてしまう

ContainerInspectが返してくる名前から`/`を取ることで対応します

**Comment by Tomo-9925** [comment]
これ，Container構造体のEqual関数側で対応していたつもりだったのですが，対応していなかったんですね…

**Comment by masibw** [comment]
結論としてコンテナ名が原因ではなくSocketのRemoteIPが設定されていないことが原因でした
判定部分にRemoteIPがなければ全てを許可するように変更するPRを作成したいと思います
